name: "bats-core"
description: "Install and run bats-core"
inputs:
  args:
    description: "args for bats-core"
    required: true
    default: "."
  directory:
    description: "the working directory"
    required: false
runs:
  using: "composite"
  steps:
    - name: bats-core
      run: |
        git clone https://github.com/bats-core/bats-core.git $HOME/bats-core
        sudo $HOME/bats-core/install.sh /usr/local

        if [ -z ${${{ inputs.directory }}+x} ]; then
          cd ${{ inputs.directory }}
        fi
        
        bats ${{ inputs.args }}
      shell: bash
